// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type BookedPractitioners struct {
	ID        uuid.UUID      `json:"id"`
	Type      sql.NullString `json:"type"`
	ServiceID uuid.NullUUID  `json:"service_id"`
	BookedFor sql.NullTime   `json:"booked_for"`
	BookedBy  uuid.NullUUID  `json:"booked_by"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type BookedVenues struct {
	ID        uuid.UUID      `json:"id"`
	Type      sql.NullString `json:"type"`
	VenueID   uuid.NullUUID  `json:"venue_id"`
	BookedFor sql.NullTime   `json:"booked_for"`
	BookedBy  uuid.NullUUID  `json:"booked_by"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Events struct {
	ID              uuid.UUID      `json:"id"`
	VenueID         uuid.NullUUID  `json:"venue_id"`
	ImageLinks      []string       `json:"image_links"`
	Name            sql.NullString `json:"name"`
	Theme           sql.NullString `json:"theme"`
	Description     sql.NullString `json:"description"`
	Audience        sql.NullString `json:"audience"`
	Activities      []string       `json:"activities"`
	CreatedBy       uuid.NullUUID  `json:"created_by"`
	StartTime       sql.NullTime   `json:"start_time"`
	StartDate       sql.NullTime   `json:"start_date"`
	EndDate         sql.NullTime   `json:"end_date"`
	TotalParticpant sql.NullInt32  `json:"total_particpant"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type Favourites struct {
	ID        uuid.UUID     `json:"id"`
	EventID   uuid.NullUUID `json:"event_id"`
	AddedBy   uuid.NullUUID `json:"added_by"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Practitioners struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ImageLink   sql.NullString `json:"image_link"`
	IsAvailable sql.NullBool   `json:"is_available"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	OpensAt     sql.NullTime   `json:"opens_at"`
	ClosesAt    sql.NullTime   `json:"closes_at"`
	WorkingDays sql.NullString `json:"working_days"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Profiles struct {
	ID           uuid.UUID      `json:"id"`
	Bio          sql.NullString `json:"bio"`
	PhoneNo      sql.NullString `json:"phone_no"`
	Country      sql.NullString `json:"country"`
	Address      sql.NullString `json:"address"`
	Experience   sql.NullInt32  `json:"experience"`
	Field        sql.NullString `json:"field"`
	BusinessName sql.NullString `json:"business_name"`
	Roles        string         `json:"roles"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type ProfilesUsers struct {
	ProfilesID uuid.UUID `json:"profiles_id"`
	UsersID    uuid.UUID `json:"users_id"`
}

type Purchases struct {
	ID          uuid.UUID     `json:"id"`
	EventID     uuid.NullUUID `json:"event_id"`
	VenueID     uuid.NullUUID `json:"venue_id"`
	ServiceID   uuid.NullUUID `json:"service_id"`
	PurchasedBy uuid.NullUUID `json:"purchased_by"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Users struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Password  sql.NullString `json:"password"`
	Firstname sql.NullString `json:"firstname"`
	Lastname  sql.NullString `json:"lastname"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Venues struct {
	ID              uuid.UUID      `json:"id"`
	ImageLinks      []string       `json:"image_links"`
	Name            string         `json:"name"`
	Type            sql.NullString `json:"type"`
	Description     sql.NullString `json:"description"`
	Location        string         `json:"location"`
	Dimension       sql.NullString `json:"dimension"`
	Capacity        sql.NullInt32  `json:"capacity"`
	Facilities      []string       `json:"facilities"`
	HasAccomodation sql.NullBool   `json:"has_accomodation"`
	RoomType        sql.NullString `json:"room_type"`
	NoOfRooms       sql.NullInt32  `json:"no_of_rooms"`
	Sleeps          sql.NullString `json:"sleeps"`
	BedType         sql.NullString `json:"bed_type"`
	Rent            sql.NullInt32  `json:"rent"`
	OwnedBy         uuid.NullUUID  `json:"owned_by"`
	IsAvailable     sql.NullBool   `json:"is_available"`
	OpensAt         sql.NullTime   `json:"opens_at"`
	ClosesAt        sql.NullTime   `json:"closes_at"`
	RentalDays      sql.NullString `json:"rental_days"`
	BookingPrice    sql.NullInt32  `json:"booking_price"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}
